#https://taskfile.dev/
version: '3'

env:
  GOLANGCI_LINT_VERSION: 1.56.0

tasks:

  tools:
    desc: 'Install all tools used in this project'
    cmds:
      - task: gofumpt
      - task: lint-check-version

  gofumpt:
    internal: true
    status:
      - which gofumpt
    cmds:
      - go install mvdan.cc/gofumpt@latest

  lint-check-version:
    internal: true
    status:
      - bin/golangci-lint --version | grep -q "{{.GOLANGCI_LINT_VERSION}}"
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b {{.TASKFILE_DIR}}/bin "v{{.GOLANGCI_LINT_VERSION}}"

  tidy:
    desc: 'run Go mod tidy'
    cmds:
      - go mod tidy

  test:
    desc: 'run Go tests'
    cmds:
      - go test ./...

  lint:
    desc: 'run Go linters'
    deps: [lint-check-version]
    cmds:
      - bin/golangci-lint run --timeout 5m --color always --max-issues-per-linter 0 --max-same-issues 0

  format:
    desc: 'formats the code'
    deps: [gofumpt]
    cmds:
      - gofumpt -l -w .

  ci:
    desc: 'do all the checks'
    cmds:
      - task: tidy
      - task: format
      - task: lint
      - task: test

  install:
    desc: 'build the project'
    cmds:
      - go build
      - go install

  run:
    desc: 'run the project'
    cmds:
      - go run . --tags integration -cover
